[package]
name = "comet-cli"
version = "0.1.6"
edition = "2021"
license = "MIT"
description = "Comet CLI"
repository = "https://github.com/Champii/Comet"

[[bin]]
path = "src/main.rs"
name = "comet"

[dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9.1"
log = "0.4.17"
colored = "2"
which = "4.3.0"
clap = "2.33.3"

