[workspace]

members = [
    "comet",
    "comet_macros/macro_procs",
    "comet_macros/macro_rules",
    "comet_bin",
]

default-members = [
    "comet",
    "comet_bin",
]

exclude = [
    "examples"
]
